// Mocks generated by Mockito 5.4.6 from annotations
// in whitebox/test/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:share_plus/share_plus.dart' as _i4;
import 'package:whitebox/services.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GallerySaverService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGallerySaverService extends _i1.Mock
    implements _i2.GallerySaverService {
  MockGallerySaverService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool?> saveImage(String? path, {String? albumName}) =>
      (super.noSuchMethod(
            Invocation.method(#saveImage, [path], {#albumName: albumName}),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);
}

/// A class which mocks [ShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareService extends _i1.Mock implements _i2.ShareService {
  MockShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> shareXFiles(List<_i4.XFile>? files) =>
      (super.noSuchMethod(
            Invocation.method(#shareXFiles, [files]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
